"""empty message

Revision ID: 8df9d58168be
Revises: 
Create Date: 2020-05-01 13:57:30.531308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df9d58168be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Participant',
    sa.Column('participant_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('participant_name'),
    sa.UniqueConstraint('participant_name')
    )
    op.create_table('Session',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('Message',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['Session.session_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('association',
    sa.Column('left_id', sa.String(length=255), nullable=True),
    sa.Column('participant_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['Message.message_id'], ),
    sa.ForeignKeyConstraint(['participant_name'], ['Participant.participant_name'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('Message')
    op.drop_table('Session')
    op.drop_table('Participant')
    # ### end Alembic commands ###
